export const LOAD_MODES = 'LOAD_MODES';
export const LOAD_VERSIONS = 'LOAD_VERSIONS';
export const LOAD_SITEVERSIONS = 'LOAD_SITEVERSIONS';
export const CREATE_SITEVERSIONS = 'CREATE_SITEVERSIONS';
export const UPDATE_SITEVERSIONS = 'UPDATE_SITEVERSIONS';
export const DELETE_SITEVERSIONS = 'DELETE_SITEVERSIONS';
export const UPLOAD_FILES_SUCCESS = 'UPLOAD_FILES_SUCCESS';
export const LOAD_FILES_SUCCESS = 'LOAD_FILES_SUCCESS';
